### ISSUE TITLE
📊 Benchmark Results: 2 * A10G (24GB)

### ISSUE THREAD

**Issue by KMouratidis** [arc53/llm-price-compass#6]
### ☁️ Cloud Provider

AWS

### 💪 GPU

Nvidia A10G

### 💸 Cost per Hour

2.836

### 🧠 Backend

vllm

### 🆔 Model ID

meta-llama/Meta-Llama-3-8B

### ⬆️ Input Throughput

2203.64

### ⬇️ Output Throughput

441.76

### 📝 Notes (Optional)

- I'm using a [g5.12xlarge](https://aws.amazon.com/ec2/instance-types/g5/) which costs $5.672/hr but I'm only using 2 * A10G GPUs with `tp=2` for the benchmark (the other 2 GPUs run a separate container with a different model), so I halved the cost.
- I'm using a proprietary fine-tuned version of meta-llama/Meta-Llama-3-8B, but the architecture is exactly the same without any differences. 

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KMouratidis** [comment]
Complete report:

```
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  97.65     
Total input tokens:                      215196    
Total generated tokens:                  43140     
Request throughput (req/s):              10.24     
Input token throughput (tok/s):          2203.64   
Output token throughput (tok/s):         441.76    
---------------Time to First Token----------------
Mean TTFT (ms):                          14807.83  
Median TTFT (ms):                        0.00      
P99 TTFT (ms):                           63343.20  
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          1041.78   
Median TPOT (ms):                        632.21    
P99 TPOT (ms):                           9019.45   
---------------Inter-token Latency----------------
Mean ITL (ms):                           343.33    
Median ITL (ms):                         96.43     
P99 ITL (ms):                            2351.83   
==================================================
```

Additional information for anyone interested:
- vllm version: 0.4.3
- Deployed on AWS ECS

**Comment by dartpain** [comment]
Thank you so much, think with spot pricing A10G on aws it can be competitive to some of the providers.
Appreciate it a lot!
